#!/usr/bin/env python
# encoding: utf-8
mysql:
     host: "www.keyou.site"
     port: 13306
     user: "lemon520"
     password: "123456"
     charset: "utf8"
     database: "test"
     cursorclass: "DictCursor"
user:
  "checkNum": 123456
  "phone": "13189770970"
  "source": "h5"
host:
  "test_url": "https://health.sina.cn/"
admin_user:
  "mobile_phone": "13189770999"
  "pwd": "12345678"

